import type { Metadata } from "next";
import { Inter, Play } from "next/font/google";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const play = Play({
  subsets: ["cyrillic"],
  weight: ["700"],
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={play.className}>{children}</body>
    </html>
  );
}
